######################站点全局信息，需要部分修改#########################
# Site settings
title: LPD-iOS
header-img: /page/img/home-bg.jpg
email: LPD-iOS@eyrefree.org
url: "https://fm612.github.io/page/"
description: "饿了么物流 iOS 开发组"
github_username: LPD-iOS
zhihu_username: 
duoshuo_id:

##########################上述信息需要您修改########3####################

# Where things are
source:       .
destination:  ./page/_site
plugins_dir:  ./page/_plugins
layouts_dir:  ./page/_layouts
data_dir:     ./page/_data
includes_dir: ./page/_includes
posts_dir: ./page/_posts
#collections:  null

# Handling Reading
safe:         false
include:      ["/page/.htaccess"]
exclude:      ["less","node_modules","Gruntfile.js","package.json","README.md","README_CN.md","tmp","unless","_resource"]
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Plugins
whitelist: []
gems:      ["jekyll-paginate"]
#gems:      []

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname

# Outputting
permalink: pretty
paginate: 16
paginate_path: /page/page/:num
timezone: Asia/Shanghai

quiet:    false
defaults: []

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  enable_coderay: true
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  input: GFM

syntax_highlighter_opts:
  wrap:              div
  line_numbers:      inline
  line_number_start: 1
  tab_width:         4
  bold_every:        10
  css:               style
